#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, counts their occurrences, and sorts the data.

myfile="apache-access.log"
awk '{print $1, $9}' "$myfile" | sort | uniq -c | sort -nr
